version: "3"
networks:
  net-alice-kms:
  net-alice:
  net-bob:
  net-public:
services:
  kms-alice:
    command: start --config /root/tmkms/tmkms.toml
    container_name: kms-alice
    image: tmkms_i:v0.12.2
    volumes:
      - ./kms-alice:/root/tmkms
    networks:
      - net-alice-kms
  val-alice:
    command: start
    container_name: val-alice
    image: checkersd_i
    volumes:
      - ./val-alice:/root/.checkers
    networks:
      - net-alice-kms
      - net-alice
    depends_on:
      - kms-alice
  sentry-alice:
    command: start
    container_name: sentry-alice
    image: checkersd_i
    volumes:
      - ./sentry-alice:/root/.checkers
    networks:
      - net-alice
      - net-public
  val-bob:
    command: start
    container_name: val-bob
    image: checkersd_i
    volumes:
      - ./val-bob:/root/.checkers
    networks:
      - net-bob
  sentry-bob:
    command: start
    container_name: sentry-bob
    image: checkersd_i
    volumes:
      - ./sentry-bob:/root/.checkers
    networks:
      - net-bob
      - net-public
  node-carol:
    command: start
    container_name: node-carol
    image: checkersd_i
    volumes:
      - ./node-carol:/root/.checkers
    networks:
      - net-public
    ports:
      - 0.0.0.0:26657:26657
      - 0.0.0.0:1317:1317
